config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    # get "sign_in", to: "sessions#new"
    # post "sign_in",   to: 'sessions#create'
    delete "sign_out", to: "sessions#destroy"
    get 'users/:id', to: 'users#new'
    get 'name', to: 'users/registrations#new_name'
    post 'name', to: 'users/registrations#create_name'
  end

  resources :users, only: :new
  resources :items do
    collection do
      get 'search'
      get 'search_tag'
    end
    resources :likes, only: [:create, :destroy]
    resources :messages
    resources :orders
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "items#index"
  delete 'items/:id' => 'itemss#destroy'

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :status
  belongs_to_active_hash :fee
  belongs_to_active_hash :form
  belongs_to_active_hash :day

  has_many :messages
  has_many :item_tag_relations, dependent: :destroy
  has_many :tags, through: :item_tag_relations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  belongs_to :user
  has_one :address
  has_one :order
  has_many_attached :images

  def self.search(search)
    if search != ''
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.order('created_at DESC')
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @items = Item.order('created_at DESC')
    @likes = Like.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = ItemTag.new(item_tag_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @messages = Message.all
    @message = Message.new
    @tagname = @item.tags[0][:tag_name]
    @like = Like.new
  end

  def edit
    @item = Item.find_by(id: params[:id])
  end

  def update
    @tag = ItemTag.new(item_tag_params)
    if @tag.update
      @item.update(tag_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    item = Item.find_by(id: params[:id])
    if item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search_tag
    return nil if params[:input] == ''

    tag = Tag.where(['tag_name LIKE ?', "%#{params[:input]}%"])
    render json: { keyword: tag }
  end

  def search
    @items = Item.search(params[:keyword])
  end

  private

  def item_tag_params
    params.require(:item).permit(
      :tag_name,
      :name,
      :explanation,
      :category_id,
      :status_id,
      :fee_id,
      :form_id,
      :day_id,
      :price,
      images: []
    ).merge(user_id: current_user.id)
  end

  def tag_params
    params.require(:item).permit(
      :name,
      :explanation,
      :category_id,
      :status_id,
      :fee_id,
      :form_id,
      :day_id,
      :price,
      images: []
    ).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find_by(id: params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages_item', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>

        <% @item.images.each do |image|%>
          <%= f.file_field :images, type: 'file', name:'item[images][]', id:"img-file", value: image %>
        <% end %>
      </div>
      <div class="image-box"></div>
    </div>
    <%# /出品画像 %>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-tag">
        <div class="weight-bold-text">
          関連タグ
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :tag_name, class:"input-tag", placeholder:"タグ名（必須）", value: @item.tags[0][:tag_name] %>
        <div id="search-result">
        </div>
      </div>
    </div>

    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:fee_id, Fee.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:form_id, Form.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する", class:"sell-btn" %>
      <%=link_to 'もどる', item_path(@item.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>
<% if user_signed_in? %>
  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', "/items/new", class: "subtitle" %>
    <ul class='item-lists'>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id), method: :get do %>
        <div class='item-img-content'>
          <%= image_tag item.images[0], class:"item_image_tag" %>
          <% if item.order.present? %>
            <div class='sold-out'>
              <span>SOLD</span>
            </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            【 <%= item.name %> 】
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円  (税込み)</span>
            <div class='star-btn'>
              <P class="heart">♥</p>
              <span class='star-count'><%= item.liked_users.count %></span>
            </div>
          </div>
        </div>
      <% end %>



      </li>

      <% end %>
    </ul>
  </div>
  <%# //商品一覧 %>
<% else %>
  <div class="signed-in">
    <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
    <div class='title-contents'>
      <h2 class='service-title'>
        人生を変えるフリマアプリ
      </h2>
      <p class='service-explain'>
        FURIMAはだれでもかんたんに出品・購入できる
      </p>
      <p class='service-explain'>
        フリマアプリです
      </p>
      <div class='store-btn'>
        <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
        <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
      </div>
    </div>
    <%# //画面上部の「人生を変えるフリマアプリ」帯部分  %>
  </div>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>

    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          最大3%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# //FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# //画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# //FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', "/items/new", class: "subtitle" %>
    <ul class='item-lists'>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id), method: :get do %>
        <div class='item-img-content'>
          <%= image_tag item.images[0], class:"item_image_tag" %>
          <% if item.order.present? %>
            <div class='sold-out'>
              <span>SOLD</span>
            </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            【 <%= item.name %> 】
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円  (税込み)</span>
            <div class='star-btn'>
              <P class="heart">♥</p>
              <span class='star-count'><%= item.liked_users.count %></span>
            </div>
          </div>
        </div>
      <% end %>



      </li>

      <% end %>
    </ul>
  </div>
  <%# //商品一覧 %>
<% end %>
</div>

<% if user_signed_in? %>
  <div class='purchase-btn'>
    <span class='purchase-btn-text'>出品する</span>
    <a href="/items/new">
      <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
    </a>
  </div>
<% else %>
  <div class='purchase-btn'>
    <span class='purchase-btn-text'>出品する</span>
    <a href="/">
      <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
    </a>
  </div>
<% end %>

<% if user_signed_in? %>
  <%= render "shared/footer-bottom" %>
<% else %>
  <%= render "shared/footer" %>
<% end %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, url: items_path, local: true do |f| %>

    <%= render 'shared/error_messages_item', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, type: 'file', name:'item[images][]', id:"img-file" %>
      </div>
      <div class="image-box"></div>
    </div>
    <%# /出品画像 %>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-tag">
        <div class="weight-bold-text">
          関連タグ
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :tag_name, class:"input-tag", placeholder:"タグ名（必須）" %>
        <div id="search-result">
        </div>
      </div>
    </div>

    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:fee_id, Fee.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:form_id, Form.all, :id, :name, {}, {class:"select-box"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する", class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/search.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class: "furima-icon"), "/" %>
      <%= form_with(url: search_items_path, class: "search-form", local: true, method: :get) do |f| %>
        <%= f.text_field :keyword, class: "input-box", placeholder: 'キーワードから探す' %>
        <%= button_tag type: 'submit', value: "", class: "search-button" do %>
        <%= fa_icon("search 2x") %>
        <% end %>
      <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', "/users/sign_out", method: :delete, class: "logout" %></li>
    <% else %>
      <li><%= link_to 'ログイン', "/users/sign_in", class: "login" %></li>
      <li><%= link_to '新規登録', "/users/sign_up", class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>

<%# 商品一覧 %>
<div class='main'>
  <div class='item-contents'>
    <h2 class='title'>検索結果</h2>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id), method: :get do %>
            <div class='item-img-content'>
              <%= image_tag item.images[0], class:"item_image_tag" %>
              <% if item.order.present? %>
                <div class='sold-out'>
                  <span>SOLD</span>
                </div>
              <% end %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                【 <%= item.name %> 】
              </h3>
              <div class='item-price'>
                <span><%= item.price %>円  (税込み)</span>
                <div class='star-btn'>
                  <P class="heart">♥</p>
                  <span class='star-count'><%= item.liked_users.count %></span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<%# //商品一覧 %>
<div class="search-to-top">
  <a href="/items" class="change-item-btn">商品一覧に戻る</a>
</div>


<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      【 <%= @item.name %> 】
    </h2>
    <div class='item-img-content-show'>
     <% @item.images.each do |image| %>
      <%= image_tag image, class:"item-box-img" %>
     <% end %>

      <% if @item.order.present? %>
        <div class='sold-out-show'>
          <span>SOLD OUT!!</span>
        </div>
      <% end %>

    </div>
    <div class="item-price-box">
      <span class="item-price-show">
        <%= @item.price %>円
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>

    <% if user_signed_in? && current_user.id == @item.user_id && !@item.order.present? %>
    <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy' %>
    <% end %>

    <% if user_signed_in? && current_user.id != @item.user_id && !@item.order.present? %>
      <%= link_to '購入画面に進む', item_order_path(@item.id), class:"item-red-btn"%>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.explanation %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <%# <%binding.pry%>
        <tr>
          <th class="detail-item">タグ</th>
          <td class="detail-value"><%= @tagname %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.fee.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.form.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.day.name %></td>
        </tr>
      </tbody>
    </table>
    <% if user_signed_in? && current_user.already_liked?(@item) %>
      <div class="option">
        <label for="star" class="label">
          <div class="favorite-btn">
              <%= button_to 'いいねを取り消す', item_like_path(@item), method: :delete, id: "star", class: "favorite" %>
              <P class="heart">♥</p>
              <span><%= @item.likes.count %></span>
          </div>
        </label>
        <div class="report-btn">
          <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
          <span>不適切な商品の通報</span>
        </div>
      </div>
    <% elsif user_signed_in? %>
      <div class="option">
        <label for="star" class="label">
          <div class="favorite-btn">
            <%= button_to 'いいね', item_likes_path(@item), id: "star", class: "favorite"%>
            <P class="heart">♡</p>
            <span><%= @item.likes.count %></span>
          </div>
        </label>
        <div class="report-btn">
          <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
          <span>不適切な商品の通報</span>
        </div>
      </div>
    <% else %>

    <% end %>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <%# <form> %>
      <%# <textarea class="comment-text"></textarea> %>
      <%= form_with model: [@item,@message], url: item_messages_path(@item), remote: true do |f| %>
        <%# <%binding.pry  %>
      <div id='messages', class='comment'>
        <% if @item.messages.present? %>
          <% @item.messages.each do |message| %><%#新しいメッセージが上に来るように回す%>
            <p class='text'><%= message.text %></p>
          <% end %>
        <% end %>
      </div>

        <%= f.text_area :text, class:"comment-text" %>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <%# <button type="submit" class="comment-btn"> %>
      <%= f.submit "コメントする", class:"comment-btn" %>
        <%# <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <%# <span>コメントする<span> %>
      <% end %>
      <%# </button> %>
    <%# </form> %>
  </div>
    <a href="/items" class="change-item-btn">商品一覧に戻る</a>
  <a href="#" class='another-item'><%= "商品のカテゴリー名" %>をもっと見る</a>
</div>

<%= render "shared/footer" %>